### ISSUE TITLE
Page does not reload automatically

### ISSUE THREAD

**Issue by vikramjit575** [eh3rrera/shopping-cart-pusher#1]
Hi,
i ran this code and its working fine but the page is not reloading automatically.For eg after adding an item in cart i have to refresh the page and after that changes are reflected in the cart.i also added spring-dev tools dependency but its not working.can you please help on that.
Thank you

**Comment by eh3rrera** [comment]
Hi @vikramjit575,

About adding items, maybe there's something wrong with your Pusher information, did you created your Pusher app in the USA cluster? Otherwise you have [to specify the cluster](https://pusher.com/docs/clusters) when creating the Pusher instance (for example, eu for Europe) In the dev console of you browser, does an error show up?

About spring-dev  tools, can you provide more detail, what do you mean is not working?

**Comment by vikramjit575** [comment]
Hi, I created the app in Mumbai cluster and I did not update it in my code.May be that's why it did not work but how would it impact the auto reload?

**Comment by eh3rrera** [comment]
Well, actually the app doesn't need to be reloaded.

When you add an item, an AJAX call is made to the server to store in the HTTP session that item and trigger a Pusher event. When that Pusher event is received on the page, React updates the interface without reloading.

And since the content cart is stored in the session, it is not lost and it's shown after reloading the page.

If you created your app in Mumbai, you have to add after the line https://github.com/eh3rrera/shopping-cart-pusher/blob/master/src/main/resources/static/js/app.js#L8: `cluster: 'ap2',`

And in the server (after line https://github.com/eh3rrera/shopping-cart-pusher/blob/master/src/main/java/com/pusher/web/CartController.java#L47): `pusher.setCluster("ap2");`

**Comment by vikramjit575** [comment]
Hi, thanks a lot:)

I finally got my issue resolved and its working fine.Have you done the same thing using webpack?I am doing it with webpack and i am struggling to run pusher and fetch in it.

 thanks a lot for getting my issue resolved

**Comment by eh3rrera** [comment]
Yes, it's very similar. You install pusher with NPM (`npm install pusher-js`) and import the module like this:
```javascript
import React, { Component } from 'react';
...
import Pusher from 'pusher-js';

export default class Index extends Component {
...
componentWillMount() {
    this.pusher = new Pusher(...);
    ...
  }
...
}
```

And your `webpack.config.js` file can be something as simple as:
```javascript
var path = require('path');

module.exports = {
  entry: ['./src/app.js'],

  output: {
    filename: 'public/js/bundle.js',
    sourceMapFilename: 'public/js/bundle.map'
  },

  devtool: '#source-map',
    
  module: {
    loaders: [
      {
        loader: 'babel',
        exclude: /node_modules/
      }
    ]
  }
}
```

Where `/src/app.js` is the starting point of your app, like:
```javascript
import React, { Component } from 'react';
import ReactDOM from 'react-dom';

import Index from './components/index';

ReactDOM.render(<Index />, document.getElementById("app"));
```

Hope it helps

**Comment by vikramjit575** [comment]
Here is a glimpse of my code

Webpack-config.js
`
var path = require('path');

module.exports = {
  entry: './src/main/resources/static/js/app.js',
  output: {
    path: __dirname + '/src/main/webapp/public', 
    filename: 'bundle.js',
    sourceMapFilename: 'bundle.map'
  },
  devtool: '#source-map',
  module: {
    loaders: [
      {
    	  test: /\.js?$/,
          exclude: /node_modules/,
          loader: 'babel-loader',
        query: {
          presets: ['es2015', 'react']
        }
      }
    ]
  },
  node: {
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
};`
 App.js
`import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import Pusher from 'pusher-js';
import Header from 'C:/Users/vikramjit.saini/Desktop/ReactWork/shopping-cart-pusher-master/src/main/resources/static/js/components/header.js';
import CartItem from 'C:/Users/vikramjit.saini/Desktop/ReactWork/shopping-cart-pusher-master/src/main/resources/static/js/components/cartItem.js';
import Cart from 'C:/Users/vikramjit.saini/Desktop/ReactWork/shopping-cart-pusher-master/src/main/resources/static/js/components/cart.js';
import Product from 'C:/Users/vikramjit.saini/Desktop/ReactWork/shopping-cart-pusher-master/src/main/resources/static/js/components/product.js';
import ProductList from 'C:/Users/vikramjit.saini/Desktop/ReactWork/shopping-cart-pusher-master/src/main/resources/static/js/components/productList.js';


var App = React.createClass({
  getInitialState: function() {
    return { items: [], products: [] };
  },
.....
  render: function() {
    return (
      <div className="container">
        <Header  />
        <Cart items={this.state.items} total={this.total} />
        <ProductList products={this.state.products} />
      </div>
    );
  }
});

ReactDOM.render(<App />, document.getElementById("app"));`

Index.html
`<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Real-time shopping cart with Pusher, Java, and React</title>

<link rel="stylesheet"
	href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<link rel="stylesheet"
	href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" />

    <link href="//cdn.muicss.com/mui-0.9.15/css/mui.min.css" rel="stylesheet" type="text/css" />
    <script src="//cdn.muicss.com/mui-0.9.15/js/mui.min.js"></script>
<link rel="stylesheet" href="/css/style.css" />
</head>
<body class="blue-gradient-background">

	<nav class="navbar navbar-inverse">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="https://pusher.com"> <img
					class="logo" src="/images/pusher-logo.png" width="111" height="37" />
				</a>
			</div>

			<p class="navbar-text navbar-right">
				<a class="navbar-link" href="http://pusher.com/signup">Create a
					Free Account</a>
			</p>
		</div>
		<div class="mui-container">
      <div class="mui-panel">
        <h1>My Title</h1>
        <button class="mui-btn mui-btn--primary mui-btn--raised">My Button</button>
      </div>
    </div>
	</nav>

	<div id="app"></div>


	
	<script th:inline="javascript">
    var PUSHER_APP_KEY = /*[[${pusher_app_key}]]*/ 'NA';
    var PUSHER_CHANNEL_NAME = /*[[${pusher_channel}]]*/ 'NA';
  </script>


  

</body>
</html>`

Also i have some doubts:

- You did not mention any dependency for fetch in webpack
-<script th:inline="javascript">
    var PUSHER_APP_KEY = /*[[${pusher_app_key}]]*/ 'NA';
    var PUSHER_CHANNEL_NAME = /*[[${pusher_channel}]]*/ 'NA';
  </script>
how this would be configured in react component?

Thanks

**Comment by eh3rrera** [comment]
All right, I see that in your configuration Webpack is creating a `bundle.js` file. This should be the JS script included in your HTML file. 

Your entry point is `app.js`, which imports the rest of the scripts, then this is where you should import fetch too.

For defining your Pusher key and channel name there a lot of options. You can hardcode them in your React class, or leave them as they are in the example and include the bundle.js script after they're defined, you can include something like an `.env.js` file, or I think Webpack can also help with its [DefinePlugin](http://webpack.github.io/docs/list-of-plugins.html#defineplugin), I don't know you can google something like _server-side variables to client-side in React_.

**Comment by vikramjit575** [comment]
Hi I am not able to run pusher and fetch through webpack.Do i need to add some loaders or anything else for them in webpack.config.js?

**Comment by eh3rrera** [comment]
No, what's the error?

**Comment by vikramjit575** [comment]
Webpack is compiling everything successfully.i don't see any error.i think there might be some plugin or something.npm pusher dependency alone is not working

**Comment by eh3rrera** [comment]
I guess I could take a look at your code sometime this week, can you upload it somewhere so I can test it?

**Comment by vikramjit575** [comment]
I am trying to run your application in with webpack and it is running successfully except these dependecies

1.import Pusher from 'pusher-js';
2.import fetch from 'fetch-js'

are not working.

**Comment by vikramjit575** [comment]
Can i use pusher and fetch cdn with webpack?

**Comment by eh3rrera** [comment]
I don't know what could be wrong.

Yes, you can use them as externals, https://webpack.github.io/docs/library-and-externals.html.

I don't mean to be rude, but maybe you should read/watch some tutorials about Webpack, this is not related to the app anymore.
